---
abstract: 'Perl interface to Yahoo Smushit image optimizer'
author:
  - 'Junior Moraes <fvox@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Yahoo-Smushit
version: 0.03
